src/Areas/oidc/Pages/Authorize.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenIddict.Abstractions;
using OpenIddict.Core;
using OpenIddict.EntityFrameworkCore.Models;
using OpenIddict.Server.AspNetCore;
using OpenIddict.RazorPages.Data;
using OpenIddict.RazorPages.Helpers;

namespace OpenIddict.RazorPages.Areas.oidc.Pages {
    // This Razor Page handles the Authorization Code, Implicit, and Hybrid flows
    [Authorize]
    public class AuthorizeModel : PageModel {
        private readonly OpenIddictApplicationManager<OpenIddictApplication> _applicationManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public AuthorizeModel(OpenIddictApplicationManager<OpenIddictApplication> applicationManager,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager) {
            _applicationManager = applicationManager;
            _signInManager = signInManager;
            _userManager = userManager;

        }


        //[BindProperty(SupportsGet = true)]
        //public string ClientId { get; set; }

        public string ApplicationName { get; set; }
        public string Scope { get; set; }

        public async Task<IActionResult> OnGetAsync() {
            // if (String.IsNullOrEmpty(ClientId)) {
            //     return BadRequest("Missing client ID.");
            // }

            var request = HttpContext.GetOpenIddictServerRequest() ??
                throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");

            var application = await _applicationManager.FindByClientIdAsync(request.ClientId) ??
                throw new InvalidOperationException("Details concerning the calling application cannot be found.");

            ApplicationName = await _applicationManager.GetDisplayNameAsync(application);
            Scope = request.Scope;

            return Page();
        }

        // User clicked Accept on the consent screen
        public async Task<IActionResult> OnPostAcceptAsync() {
            var request = HttpContext.GetOpenIddictServerRequest() ??
                throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");

            // Retrieve the profile of the logged in user.
            var user = await _userManager.GetUserAsync(User) ??
                throw new InvalidOperationException("The user details cannot be retrieved.");

            var principal = await _signInManager.CreateUserPrincipalAsync(user);

            //Note: in this sample, the granted scopes match the requested scopes
            // but you may want to allow the user to check or uncheck specific scopes
            // Simply restrict the list of scopes but calling SetScopes
            principal.SetScopes(request.GetScopes());
            principal.SetResources("resource_server");

            foreach (var claim in principal.Claims) {
                claim.SetDestinations(ClaimsHelpers.GetDestinations(claim, principal));
            }

            //Returning a signin result will ask OpenIddict to issue the appropriate access and/or identity tokens.
            return SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
        }

        // User clicked Deny on the consent screen (Default behavior, user must explicitely accept to avoid this)
        public IActionResult OnPost() => Forbid(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
    }
}

src/Areas/oidc/Pages/Logout.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenIddict.Server.AspNetCore;
using OpenIddict.RazorPages.Data;

namespace OpenIddict.RazorPages.Areas.oidc.Pages {
    //This razor page handles the Logout flows for Code and Implicit
    [Authorize]
    public class LogoutModel : PageModel {
        private readonly SignInManager<ApplicationUser> _signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager) {
            _signInManager = signInManager;

        }

        public IActionResult OnGet() {
            return Page();
        }

        // User clicked
        public async Task<IActionResult> OnPostAsync() {
            //Ask ASP.NET Core Identity to deelete the local and external cookies created
            //when the user agent is redirected from the external identity provider after
            //a successful authentication flow (e.g. Google or Facebook)
            await _signInManager.SignOutAsync();

            var properties = new AuthenticationProperties
            {
                RedirectUri = "/"
            };

            //Returning the SignOutResult will ask OpenIddict to redirect the user agent to the
            //post_logout_redirect_uri specified by the client application
            return SignOut(properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
        }
    }
}

src/Areas/oidc/Pages/Token.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenIddict.Abstractions;
using OpenIddict.Core;
using OpenIddict.EntityFrameworkCore.Models;
using OpenIddict.Server.AspNetCore;
using OpenIddict.RazorPages.Data;
using static OpenIddict.Abstractions.OpenIddictConstants;
using OpenIddict.RazorPages.Helpers;

namespace OpenIddict.RazorPages.Areas.oidc.Pages {
    //This razor page handles the token endpoint, used for Password, Authorization Code, device, and refresh flows
    [IgnoreAntiforgeryToken(Order = 1001)]
    public class TokenModel : PageModel {
        private readonly OpenIddictApplicationManager<OpenIddictApplication> _applicationManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public TokenModel(OpenIddictApplicationManager<OpenIddictApplication> applicationManager,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager) {
            _applicationManager = applicationManager;
            _signInManager = signInManager;
            _userManager = userManager;

        }

        public async Task<IActionResult> OnPost() {
            var request = HttpContext.GetOpenIddictServerRequest() ??
                throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");

            if (request.IsAuthorizationCodeGrantType() || request.IsDeviceCodeGrantType() || request.IsRefreshTokenGrantType()) {
                //Retrieve the claims principal stored in the authorization code/device code/refresh token
                var principal = (await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)).Principal;

                //Retrieve the user profile corresponding to the authorization code/refresh token
                // Note: if you want to automatically invalidate the authorization code/refresh token
                // when the user password/roles change, use the following line instead:
                var user = await _signInManager.ValidateSecurityStampAsync(principal);
                //var user = await _userManager.GetUserAsync(principal);

                if (user == null) {
                    var properties = new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.InvalidGrant,
                        [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] = "The token is no longer valid."
                    });

                    return Forbid(properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
                }

                //Ensure the user is still allowed to sign in
                if (!await _signInManager.CanSignInAsync(user)) {
                    var properties = new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.InvalidGrant,
                        [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] = "The user is not allowed to sign in."
                    });

                    return Forbid(properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
                }

                foreach (var claim in principal.Claims) {
                    claim.SetDestinations(ClaimsHelpers.GetDestinations(claim, principal));
                }

                // Returning a SignInResult will ask OpenIddict to issue the appropriate access/identity tokens.
                return SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            }

            throw new InvalidOperationException("The specified grant type is not supported.");
        }
    }
}

src/Areas/oidc/Pages/Verify.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenIddict.Abstractions;
using OpenIddict.Core;
using OpenIddict.EntityFrameworkCore.Models;
using OpenIddict.Server.AspNetCore;
using OpenIddict.RazorPages.Data;
using static OpenIddict.Abstractions.OpenIddictConstants;
using OpenIddict.RazorPages.Helpers;

namespace OpenIddict.RazorPages.Areas.oidc.Pages {
    //This razor page handles the Device Flow
    [Authorize]
    public class VerifyModel : PageModel {
        private readonly OpenIddictApplicationManager<OpenIddictApplication> _applicationManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public VerifyModel(OpenIddictApplicationManager<OpenIddictApplication> applicationManager,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager) {
            _applicationManager = applicationManager;
            _signInManager = signInManager;
            _userManager = userManager;

        }

        public string ApplicationName { get; set; }
        public string Scope { get; set; }
        public string UserCode { get; set; }

        public string Error { get; set; }
        public string ErrorDescription { get; set; }

        public async Task<IActionResult> OnGetAsync() {
            var request = HttpContext.GetOpenIddictServerRequest() ??
                throw new InvalidOperationException("The OpenID Connect request cannot retrieved.");

            //If the user code was specified in the query string (e.g. as part of the verification_uri_complete),
            //render a form to ask the user to enter the user code manually (non-digit characters are automatically ignore)
            if (string.IsNullOrEmpty(request.UserCode)) {
                return Page();
            }

            //Retrieve the claims principal associated with the user code.
            var result = await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            if (result.Succeeded) {
                //Retrieve the application details from the database using the client_id stored in the principal
                var application = await _applicationManager.FindByClientIdAsync(result.Principal.GetClaim(Claims.ClientId)) ??
                    throw new InvalidOperationException("Details concerning the calling client application cannot be found.");

                ApplicationName = await _applicationManager.GetDisplayNameAsync(application);
                Scope = string.Join(" ", result.Principal.GetScopes());
                UserCode = request.UserCode;
                return Page();
            }

            //If the input code is not valid, redisplay the form
            Error = result.Properties.GetString(OpenIddictServerAspNetCoreConstants.Properties.Error);
            ErrorDescription = result.Properties.GetString(OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription);
            return Page();
        }

        // User clicked Accept on the consent screen
        public async Task<IActionResult> OnPostAcceptAsync() {
            //Get the logged in user's profile
            var user = await _userManager.GetUserAsync(User) ??
                throw new InvalidOperationException("The user details cannot be retrieved.");

            //Retrieve the claims principal associated with the user code
            var result = await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            if (result.Succeeded) {
                var principal = await _signInManager.CreateUserPrincipalAsync(user);

                // Note: in this sample, the granted scopes match the requested scope
                // but you may want to allow the user to uncheck specific scopes.
                // For that, simply restrict the list of scopes before calling SetScopes.
                principal.SetScopes(result.Principal.GetScopes());
                principal.SetResources("resource_server");

                foreach (var claim in principal.Claims) {
                    claim.SetDestinations(ClaimsHelpers.GetDestinations(claim, principal));
                }

                var properties = new AuthenticationProperties
                {
                    //This property points to the address OpenIddict will automatically
                    //redirect the user to after validating the authorization command.
                    RedirectUri = "/"
                };

                return SignIn(principal, properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            }

            //If the input code is not valid, redisplay the form
            Error = result.Properties.GetString(OpenIddictServerAspNetCoreConstants.Properties.Error);
            ErrorDescription = result.Properties.GetString(OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription);
            return Page();

        }


        // User clicked Deny on the consent screen (Default behavior, user must explicitely accept to avoid this)
        public IActionResult OnPost() {
            var properties = new AuthenticationProperties
            {
                //This property points to the address OpenIddict will automatically
                //redirect the user to after validating the authorization command.
                RedirectUri = "/"
            };

            return Forbid(properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
        }
    }
}

src/Areas/oidc/Pages/Authorize.cshtml
@page
@model AuthorizeModel
@using Microsoft.Extensions.Primitives

<div class="jumbotron">
    <h1>Authorization</h1>

    <p class="lead text-left">Do you want to grant <strong>@Model.ApplicationName</strong> access to your data? (scopes requested: @Model.Scope)</p>

    <form asp-controller="Authorization" asp-action="Authorize" method="post">
        @* Flow the request parameters so they can be received by the Accept/Reject actions: *@
        @foreach (var parameter in HttpContext.Request.HasFormContentType ?
            (IEnumerable<KeyValuePair<string, StringValues>>) HttpContext.Request.Form : HttpContext.Request.Query)
        {
            <input type="hidden" name="@parameter.Key" value="@parameter.Value" />
        }

        <input class="btn btn-lg btn-success" asp-page-handler="accept" type="submit" value="Yes" />
        <input class="btn btn-lg btn-danger" type="submit" value="No" />
    </form>
</div>

src/Areas/oidc/Pages/Logout.cshtml
@page
@model LogoutModel
@using Microsoft.Extensions.Primitives

<div class="jumbotron">
    <h1>Log out</h1>
    <p class="lead text-left">Are you sure you want to sign out?</p>

    <form asp-controller="Authorization" asp-action="Logout" method="post">
        @* Flow the request parameters so they can be received by the LogoutPost action: *@
        @foreach (var parameter in HttpContext.Request.HasFormContentType ?
           (IEnumerable<KeyValuePair<string, StringValues>>) HttpContext.Request.Form : HttpContext.Request.Query)
        {
            <input type="hidden" name="@parameter.Key" value="@parameter.Value" />
        }

        <input class="btn btn-lg btn-success" name="Confirm" type="submit" value="Yes" />
    </form>
</div>

src/Areas/oidc/Pages/Token.cshtml
@page
@model TokenModel

src/Areas/oidc/Pages/Verify.cshtml
@page
@model VerifyModel
@using Microsoft.Extensions.Primitives

<div class="jumbotron">
    <h1>Authorization</h1>

    @if (string.IsNullOrEmpty(Model.UserCode) || !string.IsNullOrEmpty(Model.Error))
    {
        @if (!string.IsNullOrEmpty(Model.Error) && !string.IsNullOrEmpty(Model.ErrorDescription))
        {
            <p class="lead text-center alert alert-warning">
                An error occurred:
                <br />
                @Model.ErrorDescription (@Model.Error)
            </p>
        }

        <p class="lead text-left">Enter the user code given by the client application:</p>

        <form asp-controller="Authorization" asp-action="Verify" method="get">
            <div class="form-check">
                <input class="form-control" name="user_code" type="text" />
            </div>

            <input class="btn btn-lg btn-success" asp-page-handler="accept" type="submit" value="Submit" />
        </form>
    }
    else
    {
        <p class="lead text-left">Do you want to grant <strong>@Model.ApplicationName</strong> access to your data? (scopes requested: @Model.Scope)</p>
        <p class="lead text-center alert alert-warning">
            Make sure that the code displayed on the device is <strong>@Model.UserCode</strong>.
            <br />
            If the two codes don't match, press "No" to reject the authorization demand.
        </p>

        <form asp-controller="Authorization" asp-action="Verify" method="post">
            @* Flow the request parameters so they can be received by the VerifyAccept/VerifyReject actions: *@
            @foreach (var parameter in HttpContext.Request.HasFormContentType ?
                (IEnumerable<KeyValuePair<string, StringValues>>) HttpContext.Request.Form : HttpContext.Request.Query)
            {
                <input type="hidden" name="@parameter.Key" value="@parameter.Value" />
            }

            <input class="btn btn-lg btn-success" asp-page-handler="accept" type="submit" value="Yes" />
            <input class="btn btn-lg btn-danger" type="submit" value="No" />
        </form>
    }
</div>